### ISSUE TITLE
wg0.conf 

### ISSUE THREAD

**Issue by FaboulousSan** [shuricksumy/docker-wgdashboard#32]
Hello, and thank you very much for your work!

I am encountering an issue with the volume configuration for my WireGuard and wg-dashboard containers. Both containers are currently using the same volume:

    /opt/wireguard/config:/etc/wireguard

This setup leads to a conflict where wg-dashboard may overwrite the wg0.conf file created by WireGuard, causing connectivity issues. Additionally, when attempting to add a peer, the dashboard redirects back to the login page.

To resolve these issues, I plan to create a synchronization script that will copy the wg0.conf file from the WireGuard container to a separate directory for wg-dashboard. This way, wg-dashboard can access the correct configuration file without overwriting or interfering with WireGuard's settings.

```
==> /opt/wireguarddashboard/app/src/log/error_2024_11_02_02_07_10.log <==
[2024-11-02 02:08:19,627] ERROR in app: Exception on /api/getAvailableIPs/wg0 [GET]
Traceback (most recent call last):
  File "/opt/wireguarddashboard/app/src/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wireguarddashboard/app/src/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wireguarddashboard/app/src/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/opt/wireguarddashboard/app/src/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wireguarddashboard/app/src/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wireguarddashboard/app/src/dashboard.py", line 1911, in API_getAvailableIPs
    status, ips = _getWireguardConfigurationAvailableIP(configName)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/wireguarddashboard/app/src/dashboard.py", line 1403, in _getWireguardConfigurationAvailableIP
    addressSplit, cidr = i.split('/')
    ^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by shuricksumy** [comment]
Hi,

I have not got your idea about using the same wh0.conf. Could you explain it in details. You can always set different mount point on local machine in composer file to separate configurations. like
/opt/wireguard/config_1:/etc/wireguard.

As to logout. I faced this issue also. You can just clean cookies and cash in browser connected to url of your web application wgdashboard.

Please let me know if it helps you

**Comment by FaboulousSan** [comment]
Hi,

Hi,

Thank you for taking the time to respond. I think I didn't fully understand how wgdashboard works and how it retrieves information from WireGuard. When I connect with peer1 from wg0, it works fine, but I don't see it online on the dashboard.

Could you explain this in more detail? It would really help me out.

Thanks again!

**Comment by shuricksumy** [comment]
Please ensure that you vpn connection works. It depends on iptables setting but in general just open any url from the Internet while you are connected to vpn. it should open url and also you will see in client some statistic Rx/Tx for trafik. If all this work It should show your client as active on dashboard.
